### ISSUE TITLE
About Boundary Loss

### ISSUE THREAD

**Issue by ZhiqingMiao** [huixiancheng/SENet#1]
Nice work! Thank u for releasing this repo!
I would like to ask a few questions about BoundaryLoss~

1. Does BoundaryLoss consume a lot of time in your experiments? In my experiments, computing the Boundaryloss consumes a lot of GPU memory and triples the training time. 
2.  I don't use the range image method to represent the point cloud, but use the BEV two-dimensional representation, could the BoundaryLoss be used to train the network? 

Thanks in advance for your reply!

**Comment by huixiancheng** [comment]
Hi. 
For 1: In my experiments, it does not take up too much video memory (10.9→11.5) or adds  too much  training time (15min→17min).
For 2: Although I doubt the validity of bd loss, it deserves to be useful from a visualization point of view. I updated the code for bd loss, you can vis GT and Pred edges from it. Where classes from 0→20 corresponds to 20 seg_cls of SemanticKITTI. (unlabeled, car, bicycle and etc.)
https://github.com/huixiancheng/SENet/blob/438d8093c7e5c65158c2e84901e57b7d8519abb8/modules/losses/boundary_loss.py#L58-L65
Some visualization of GT edges:
![vis](https://user-images.githubusercontent.com/65054204/160217089-557ea795-ce7a-4398-b127-39507507a553.png)

I think if you can see clear boundaries in the BEV view, you can take a try.

**Comment by ZhiqingMiao** [comment]
Thank you for your reply! It helped me a lot.

**Comment by jialeli1** [comment]
Hi!
How much mIoU improvement does the boundary loss bring? @huixiancheng 
It doesn't seem to converge for my experiments (0.97 -> 0.72 for 24 training epochs).

**Comment by huixiancheng** [comment]
@jialeli1 
I tested it on other models and it brought about 1.8miou improvement. In my experiments, this loss decreases from 0.99 to 0.55 in 30 epochs. Perhaps the weighted value is a matter to consider.
