### ISSUE TITLE
train paramter

### ISSUE THREAD

**Issue by fengluodb** [huixiancheng/SENet#10]
https://github.com/huixiancheng/CENet/blob/1ca48f1e9a6547d4361b921b491930b53ed681dd/config/arch/senet-2048p.yml#L67-L78
I have a question about these paramter.  Your paramter is different from darknet which used.  Will these paramter increase the model accuracy after you change it.

**Comment by huixiancheng** [comment]
Refer to issue #6. I didn't test its impact on performance. Perhaps it may slightly affect the performance of some classes.

**Comment by fengluodb** [comment]
Thank you for your reply. I have another quesetion about model train. Can you tell me how big do you usually set `batchsize`, `H, W` when you do experiment.

**Comment by huixiancheng** [comment]
Limited by resources, I usually start experiments with a resolution of 64*512. Training is faster with this setting.
For batchsize, just make full use of the GPU under amp as much as possible.

**Comment by fengluodb** [comment]
When I use amp, loss will be nan after 4~5 epoch. Do you meet the condition?

**Comment by huixiancheng** [comment]
No, I have not met it on this codebase. However, I have met this problem on other codebases, see this [issue](https://github.com/ICEORY/PMF/issues/8). In that example, nan was caused by a numerical overflow.

**Comment by fengluodb** [comment]
Thank you. Your project and reply help me a lot.
