### ISSUE TITLE
AttributeError: type object 'Trainer' has no attribute 'save_to_log'

### ISSUE THREAD

**Issue by liaozhihao2757** [huixiancheng/SENet#11]
Traceback (most recent call last):
  File "train.py", line 133, in <module>
    trainer.train()
  File "/home/buaa/project_liaozhihao/CENet-main/modules/trainer.py", line 336, in train
    Trainer.save_to_log(logdir=self
AttributeError: type object 'Trainer' has no attribute 'save_to_log'

I found this issue when the code is training and this “Trainer.save_to_log” is not found in the Class Trainer.

**Comment by huixiancheng** [comment]
Sorry for missing this part. Maybe fixed by upload this part. Welcome try again.

**Comment by liaozhihao2757** [comment]
Is this related to the pytorch version, I am using the pytorch 1.9 and cuda 11.3

**Comment by huixiancheng** [comment]
No. It just caused by code missing.

**Comment by huixiancheng** [comment]
However, if y don't use tensorboard or save scan in valid, this part is useless.

**Comment by liaozhihao2757** [comment]
okk, thank you very much.
