### ISSUE TITLE
After infer.py and evaluate_iou.py, the IoU are all 0.000. But the IoU result in train.py are normal value

### ISSUE THREAD

**Issue by liaozhihao2757** [huixiancheng/SENet#12]
['train', 'valid', 'test'] set:
Acc avg 0.001
IoU avg 0.000
IoU class 1 [car] = 0.000
IoU class 2 [bicycle] = 0.000
IoU class 3 [motorcycle] = 0.001
IoU class 4 [truck] = 0.000
IoU class 5 [other-vehicle] = 0.000
IoU class 6 [person] = 0.000
IoU class 7 [bicyclist] = 0.000
IoU class 8 [motorcyclist] = 0.000
IoU class 9 [road] = 0.000
IoU class 10 [parking] = 0.000
IoU class 11 [sidewalk] = 0.000
IoU class 12 [other-ground] = 0.000
IoU class 13 [building] = 0.000
IoU class 14 [fence] = 0.000
IoU class 15 [vegetation] = 0.000
IoU class 16 [trunk] = 0.000
IoU class 17 [terrain] = 0.000
IoU class 18 [pole] = 0.000
IoU class 19 [traffic-sign] = 0.000
********************************************************************************
below can be copied straight for paper table
0.000,0.000,0.001,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.001

在训练阶段的日志预测结果一切正常，但是针对验证集执行infer.py和evaluate_iou.py，之后得到预测结果都是0，并且训练多次也是这样。我下载了您提供的预训练模型512-594和512-valid，执行推理评估后的预测结果也是正常的。

我发现预测结果文件夹里，sequences/08/predictions，我的训练模型推理的结果都是二进制文件，而预训练模型推理的结果有二进制文件也有pcx图像，如下图所示。

请问您知道是什么原因吗？期待您的解答！
![1](https://user-images.githubusercontent.com/70627831/199003979-249e6d41-d4e4-40a1-bdf3-d35a7e192a5f.jpg)
![2](https://user-images.githubusercontent.com/70627831/199004003-f281a6b8-e83f-41e8-b63e-1f1c3daf12ad.jpg)

**Comment by liaozhihao2757** [comment]
I suspect it may be because my trained model is trained with multiple GPUs and the provided pre-trained model is trained with a single GPU, thus causing errors during the inference and evaluation phases.

**Comment by huixiancheng** [comment]
可能是这个原因，我不太确定，因为一直设定单卡训练. 这个像是没加载到预训练模型
你在这个地方设置了`strict=False`? 正常情况下单卡加载多卡训练模型会报错的。**（模型在DataParallel或者DDP训练后保存的键值有module. ，对应的网络的键值则没module.）**  这种的话百度下修改移除键值中的module就行
https://github.com/huixiancheng/CENet/blob/a466bcc0db51c9299709a710a496f3b4839d707f/modules/user.py#L72-L75
If that is true, maybe here two possible solutions.

或者直接多卡加载应该也行：
~~~
    self.model = nn.DataParallel(self.model)
    w_dict = torch.load(modeldir + "/SENet_valid_best",
                        map_location=lambda storage, loc: storage)
    self.model.load_state_dict(w_dict['state_dict'], strict=True)
~~~

**Comment by liaozhihao2757** [comment]
Thank you for your reply! It‘s very useful for this issuse! I solved the problem after Multiple GPUs loading!
