### ISSUE TITLE
The IoU value of the valid sets in training logs is inconsistent with the IoU value obtained from the infer.py and evaluate_iou.py

### ISSUE THREAD

**Issue by liaozhihao2757** [huixiancheng/SENet#13]
在训练时我发现日志里的验证集（sequence 08）的最佳mIoU，与在推理评估模型后得到的mIoU值不相同。之后我对第100个epoch保存的模型进行推理评估，也与日志里的值不相同。请问您遇到类似问题吗，期待您的解答！

**Comment by huixiancheng** [comment]
训练时的验证结果是在2D上计算的，投影回3D点后会有损失，所以mIoU会低一点，分辨率越低的话，掉的会越多一点。详情可以参考Rangnet++的论文和Repo。
