### ISSUE TITLE
About do_range_projection

### ISSUE THREAD

**Issue by starnstar** [huixiancheng/SENet#15]
Hello,

In common/laserscan.py, you used fov_down to calculate proj_y:

        # get projections in image coords
        proj_x = 0.5 * (yaw / np.pi + 1.0)  # in [0.0, 1.0]
        proj_y = 1.0 - (pitch + abs(fov_down)) / fov  # in [0.0, 1.0]

but in the paper, there is f_up:
![image](https://user-images.githubusercontent.com/30718333/200727608-b2fbe455-960f-4356-a938-579221e1d0c9.png)

I am confused about why there is fov_down rather than f_up? Thanks a lot.

**Comment by starnstar** [comment]
Solved.

**Comment by huixiancheng** [comment]
It's a interesting question. Which I do you think it's right?
In RangeNet++ paper, it's' f_up:
![a](https://user-images.githubusercontent.com/65054204/200988032-044748a4-8f1b-4c62-9f83-f541e6b40051.png)

In SalsaNext paper, it's f_down:
![b](https://user-images.githubusercontent.com/65054204/200988092-20b0ada1-bfca-4f29-a5c1-4348f7ad3aed.png)

**Comment by starnstar** [comment]
Thanks for your reply.

After formula derivation by myself, The correct formula is:
![image](https://user-images.githubusercontent.com/30718333/200988537-485ef46f-f494-4477-b25f-c46431ce0a91.png)

So the code part is right, but the formula in RangeNet++ is wrong.
It is really an interesting thing while I am reading the paper and the code. If you are interested, you can also check.

Best regards.

**Comment by huixiancheng** [comment]
Yep, I agree that. Thank for point out, this taught me a lesson.
