### ISSUE TITLE
Is Paper Available at arXiv

### ISSUE THREAD

**Issue by ldkong1205** [huixiancheng/SENet#2]
Congrats on your work!

Is your paper available on arXiv now? Could you share a pre-print with me? Thanks!

**Comment by huixiancheng** [comment]
Hi, thank you for your interest. Very sorry I can't upload to arxiv. However, I upload a orginal version of paper in assert. 
You can refer to it, actually it's really a simple incremental work.

**Comment by ldkong1205** [comment]
Great! Thank you for providing your pre-print and also open-sourcing the code.
