### ISSUE TITLE
question for environment setting

### ISSUE THREAD

**Issue by HiMarumo** [huixiancheng/SENet#23]
Thank you for your remarkable work. 
I want to run this program, but where can I find the reference for environment settings (such as requirements.txt)?

**Comment by huixiancheng** [comment]
Sorry, as this experiment was conducted on an online GPU server, I can no longer export the environment settings.
However, we don't use any special packages in our code, so maybe you can create a new conda environment, install torch, numpy, opencv and then install other packages based on the debug results.

**Comment by HiMarumo** [comment]
I was able to execute the program successfully. Thank you very much!
