### ISSUE TITLE
visualization problem

### ISSUE THREAD

**Issue by FanZhang91** [huixiancheng/SENet#24]
When I run visualize.py to view seg results, but the conversation interface did not appear with no error. Just like in the following figure。
![image](https://user-images.githubusercontent.com/21361349/234774348-84c5427a-ab0d-4863-9c68-3638ab62f166.png)

**Comment by huixiancheng** [comment]
Sry. Not checked this part in ubuntu. There may be problems if you run the code using an ssh remote connection.
