### ISSUE TITLE
About visualization

### ISSUE THREAD

**Issue by ZhiqingMiao** [huixiancheng/SENet#4]
当我使用您的代码进行可视化时，输出这样的结果，并没有可视化的界面出现，请问您知道是什么原因吗？期待您的解答！
When I use your code for visualization, the output is like this, and no visual interface appears. Do you know the reason? Looking forward to your answer!
```
(polarnet) miao@dongtintech-rtx2080ti:~/Music/CENet-main$ python visualize.py -w kitti -d /home/miao/Music/PolarSeg-master/data/ -s 08
********************************************************************************
INTERFACE:
Dataset Type kitti
Dataset /home/miao/Music/PolarSeg-master/data/
Sequence 08
Predictions None
ignore_semantics False
ignore_safety False
offset 0
********************************************************************************
Opening config file of KITTI
Sequence folder exists! Using sequence from /home/miao/Music/PolarSeg-master/data/sequences/08/velodyne
Labels folder exists! Using labels from /home/miao/Music/PolarSeg-master/data/sequences/08/labels
WARNING: Although tkinter is already imported, the tkinter backend could not
be used ("Could not import Tkinter or pyopengltk, module(s) not found."). 
Note that running multiple GUI toolkits simultaneously can cause side effects.
Using semantics in visualizer
/home/miao/anaconda3/envs/polarnet/lib/python3.7/site-packages/vispy/gloo/texture.py:28: UserWarning: GPUs can't support floating point data with more than 32-bits, precision will be lost due to downcasting to 32-bit float.
  warnings.warn(F64_PRECISION_WARNING)
To navigate:
        b: back (previous scan)
        n: next (next scan)
        q: quit (exit program)
```

**Comment by huixiancheng** [comment]
Hi. I recheck this part in my case. Look like it's no problem in Windows. 
Some key environments: python: 3.6.12 vispy: 0.9.4 matplotlib: 3.3.3
Maybe you should check this part of warning:
~~~
WARNING: Although tkinter is already imported, the tkinter backend could not
be used ("Could not import Tkinter or pyopengltk, module(s) not found."). 
Note that running multiple GUI toolkits simultaneously can cause side effects.
~~~
![QQ截图20220415233204](https://user-images.githubusercontent.com/65054204/163672377-6d01867b-227c-4ccb-b8f6-7f517abb3410.png)

**Comment by ZhiqingMiao** [comment]
感谢您的回复！这对我很有帮助！我在安装pyopengltk后解决了问题！
Thank you for your reply! This is very helpful for me! I solved the problem after installing pyopengltk!

**Comment by huixiancheng** [comment]
Great to hear that！

**Comment by ZhiqingMiao** [comment]
请问为什么，用自己的算法生成验证集上的预测标签时，在可视化时，调色方案会是下图这样呢？![image](https://user-images.githubusercontent.com/55646325/165911803-07906c88-6faa-4a98-aa52-262126c97f23.png)
请问如何设置才能让产生的预测标签颜色与下图（直接查看ground truth）配色方案一样？ 期待您的回复~
![image](https://user-images.githubusercontent.com/55646325/165912182-5ac1bf6e-6731-489c-a759-980e11a932b9.png)

**Comment by huixiancheng** [comment]
You can check this part of **color map(color_dict**) which from semantic-kitti.yaml.
https://github.com/huixiancheng/CENet/blob/d9f2339c689d695d3ab304c601423c845a5dc543/visualize.py#L149-L153
By the way, I think it's unlikely that the color table is wrong, it's very likely that you have a problem with the label or **label mapping(See this part)**. https://github.com/huixiancheng/CENet/blob/d9f2339c689d695d3ab304c601423c845a5dc543/modules/user.py#L214-L215

**Comment by liaozhihao2757** [comment]
I am also running the code on the linux system but there is no pop-up window. After installing the pyopengltk library, the problem has not been addressed. Can I refer to your library directory?

**Comment by ZhiqingMiao** [comment]
![image](https://user-images.githubusercontent.com/55646325/227749515-7f337c76-2b2c-4f27-8f3b-d94067ac7e9b.png)
您好，请问如何可以获得图中右侧两个图片中的预测mistake标记图呢？期待您的回答，感谢！

**Comment by huixiancheng** [comment]
Please refer to issue #18.
