### ISSUE TITLE
Config parameters are strange.

### ISSUE THREAD

**Issue by SYSUGrain** [huixiancheng/SENet#6]
These parameters are different with SalsaNext. Can you explain it? Thx.
img_means: #range,x,y,z,signal
      - 11.71279
      - -0.1023471
      - 0.4952
      - -1.0545
      - 0.2877
img_stds: #range,x,y,z,signal
      - 10.24
      - 12.295865
      - 9.4287
      - 0.8643
      - 0.1450

**Comment by huixiancheng** [comment]
Hi! This part of the [config in SalsaNext](https://github.com/Halmstad-University/SalsaNext/blob/a02fad97d646d4c132266ab79fbaea3ecfc237ed/salsanext.yml#L55-L66) is simply from RangNet++. 
However, you will find [some discussions](https://github.com/PRBonn/lidar-bonnetal/issues?q=img_means) in Rangnet++'s repo about that the img_means calculate wrong. So I just use the data reported [here](https://github.com/PRBonn/lidar-bonnetal/issues/16#issuecomment-718550999).

**Comment by SYSUGrain** [comment]
Thanks for your reply! Do you mind share your email for me? I have some other things to discuss with you.

**Comment by SYSUGrain** [comment]
Thanks for your reply! Do you mind sharing your email for me? I have some other things to discuss with you.

**Comment by huixiancheng** [comment]
This is my email: chenghuixian@email.swu.edu.cn. Welcome discuss.
