### ISSUE TITLE
downsample

### ISSUE THREAD

**Issue by fengluodb** [huixiancheng/SENet#9]
https://github.com/huixiancheng/CENet/blob/1ca48f1e9a6547d4361b921b491930b53ed681dd/modules/network/ResNet.py#L111-L114

I have a question about the net design, why don't expand the output channel when the downsample. In rangenet, squeezesegv3, salsanext, they all expand channel size to double when downsample. In your net, keeping channel size same when downsample don't lose feature ?

**Comment by huixiancheng** [comment]
It's just simply from FIDNet. I think the original author used this setting to keep the amount of parameters. However, maybe use the original resnet34 (like what you say) may get a better performance.
